name: Get Telegram Code Manual

on:
  workflow_dispatch:

jobs:
  fetch-number:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Requests
      run: pip install requests

    - name: Run Automation
      env:
        FIVESIM_API_KEY: ${{ secrets.FIVESIM_API_KEY }}
      run: python main.py
